### PR TITLE
Use default post and comment visibility for anonymous readers

### PR DESCRIPTION
**Pull request by xrpd**
This patch is intended to resolve issue #555.

Two new '.ini' file globals are introduced (default_min_link_score, default_min_comment_score).  These are used to initialize user preferences (pref_min_link_score, pref_min_comment_score), and are used when the reader is not logged in (is an anonymous reader).  For consistency, the 'hide_comment_threshold' global is no longer used - pref_min_comment_score or default_min_comment_score are used instead as appropriate.

Tested as various users, logged in and logged out.  Works with posts and comments in main and discussion.

### CODE REVIEW

**Comment by cdaloisio** [comment]
https://github.com/tricycle/lesswrong/issues/555#issuecomment-184848390

If `hide_comment_threshold` is no longer being used, could it be removed?

**Comment by xrpd** [comment]
Will do.  I was just wary of deleting configuration options without encouragement.

**Comment by xrpd** [comment]
@cdaloisio hide_comment_threshold removed per your suggestion.

**Comment by cdaloisio** [comment]
Thanks @xrpd :+1: Closes #555

**Comment by xrpd** [comment]
Thanks @cdaloisio!  Just wanted to be sure you knew that this one needs new production config file entries as well.  Something like ...

default_min_link_score = -2
default_min_comment_score = -2

I'm looking at the list of lesswrong discussion posts while logged out, and I'm still seeing some heavily downvoted posts, so I'm thinking that these parameters aren't being set.

**Comment by cdaloisio** [comment]
Yes I've included these values in `production.ini`. I haven't deployed the latest 2 PR's yet. It should be live in the next 10 minutes or so :smile:

**Comment by xrpd** [comment]
Sorry :blush: no rush, thanks for keeping lw running smoothly.

**Pull request merged**
