### PR TITLE
Implement per-user vote multiplier. Fixes #568

### LINKED ISSUE #568: Accounts have equal voting power
Right now, all accounts count for the same amount of karma (1) when they vote. This should be replaced with a non-negative account variable, called "weight" or something similar, which is adjustable from the user page by anyone logged in as admin.

1. I suspect that a basic solution for the change to voting dynamics just necessitates changing line 85 of [this file](https://github.com/tricycle/lesswrong/blob/master/r2/r2/models/vote.py).

2. It's not as clear to me how to create the UI element to adjust the weight on the userpage, but it should be place by the other buttons that are only visible to admins.

Further **optional** elements:

3. Make the weight visible to everyone on the userpage, in a similar fashion to the total karma and karma over last 30 days bubbles.

4. Make new accounts start with a weight of 0, which increases to 1 at 10 karma. (This will allow us to revert #550 and close #560.)

This issue is *just* for changing new vote values. It seems likely that changing old votes will require a batch job, which will get put in a separate issue.

### PR DESCRIPTION
**Pull request by jglamine**
Admins can assign users a vote multiplier. The default value is 1. It must be an integer >= 0.

Vote multiplier effects future votes, but not past votes.
If it is not 1, a user's vote multiplier shows up on their user page. All users can see everyone else's vote multiplier.

If a user has a multiplier of 0 they can still vote, but their votes do not award any karma. (let me know if you want me to change this)

There is one known issue where if your vote multiplier is changed and you go back to view an old comment which you voted on, it will appear as if the old vote includes the multiplier even though it doesn't. Re-voting and then reloading the page solves the issue. Since this is just a minor UX issue with a non-trivial fix, I don't think we should worry about it. We can always fix it later if we want to.

### CODE REVIEW

**Comment by jglamine** [comment]
This passes the manual tests.

**Comment by jglamine** [comment]
sidebar
A user's vote multiplier is displayed in the sidebar.

**Comment by jglamine** [comment]
edit-multiplier
Admins can see a "Vote multiplier" link. Clicking it brings them to this page.

Submitting the form redirects you to the user overview page.

**Comment by wezm** [comment]
Thanks for the PR, I've done some reviewing and have a few things that need to be addressed:

* Given this is an admin only feature I don't think there's any need for a CAPTCHA
* The form doesn't render particularly well (layout, see screenshot below) and could use some tidying up
* The error message is shown in the wrong place
* The error messages refers to award amount, when you are setting a multiplier
* I don't think a 0 multiplier makes sense, so would suggest requiring it to be > 0
* The positioning of the label in the sidebar is a bit ugly due to the text being hard up against the buttons. Are you able to explore some alternatives that avoid this
* Suggest using a multiplication character `⨉` instead of `x` in the label.

screen shot 2016-08-16 at 12 13 37 pm
screen shot 2016-08-16 at 12 20 00 pm

**Comment by jglamine** [comment]
Thanks for reviewing this, that's all really helpful feedback.  I'll take a look at fixing these issues in a week or so once I'm back from vacation.

My understanding is that we want the ability to give an account a multiplier of 0 in order to make their votes not count. I agree that this is strange and it might make more sense to have a voting permission toggle instead, although that would take additional development time. I think we can leave that as a future improvement.

I'll remove the captcha and try some formatting changes.

Where do you want the error message to be?

**Comment by vaniver** [comment]
Yeah, a main reason to have this is giving a 0 multiplier to use on accounts we want to disenfranchise.

I also think it's better UX to store votes from new users and not count them, then increasing the weight when they hit a karma threshold. This PR doesn't do that (we currently just have voting shut off for low karma accounts) but it sets it up so that's easier to implement.

**Comment by jglamine** [comment]
PR updated.

- Removed captcha.
- Fixed form input/button alignment, moved error text to be left-justified.
- Added custom error message text.
- Switched to unicode `⨉` character.
- Moved vote multiplier label, changed color to grey (if you want it green, let me know)

form
error-missing
error-int
negetive-error
sidebar


If you still see formatting issues on the form, let me know what browser you're using so I can reproduce it.

**Comment by wezm** [comment]
This also looks good to go now. Will also deploy tomorrow.

**Comment by jglamine** [comment]
Sweet!

**Comment by wezm** [comment]
Deployed

**Pull request merged**
