### PR TITLE
Add the ability to submit links. Fixes #548

### LINKED ISSUE #548: Linkposts not enabled
The functionality to make link pages might still exist (see NewLink in pages.py as an example of a fragment), just not be used anywhere.

The link submit page should be available from a button below the 'create new article' button. (It can either be a separate page, or another tag on the submit page link it is in Reddit.) Link submissions should only be possible to Discussion.

### PR DESCRIPTION
**Pull request by jglamine**
This turned out to be non-trivial. I'm not sure what tricycle's release process is like, but someone other than me should probably do some additional regression testing.

I suggest using this link to view the diff while ignoring whitespace changes: https://github.com/tricycle/lesswrong/pull/575/files?w=1

### CODE REVIEW

**Comment by jglamine** [comment]
home

Link posts are automatically prefixed with "[Link]". There is a new "Submit a new link" button on the sidebar.

**Comment by jglamine** [comment]
submit-post
The submit page has two tabs.

**Comment by jglamine** [comment]
submit-link

**Comment by jglamine** [comment]
link-page
Clicking on "comments" brings you to this page.

**Comment by jglamine** [comment]
edit-link
The edit link page allows you to change the title but not the url.

**Comment by wezm** [comment]
I would be great if you could take some time to increase your confidence that this won't break the site. At the very least there is a manual test script that goes through the core activities of the system:

https://github.com/tricycle/lesswrong/wiki/Hacking-on-Less-Wrong#manual-tests

Additionally, since this changes the link model, which is the core model of the application it will be worth poking at all the places links and comments are shown such as the main listings, sidebar, RSS feeds, user messages, the front page, user profile page listings.

--
Wesley Moore
Senior Developer
ph: +61 3 9024 2760
TrikeApps <http://trikeapps.com/>

**Comment by jglamine** [comment]
Good idea, will do.

**Comment by jglamine** [comment]
I fixed a few issues with rss feeds, side-bar, and front page links not being correct (linking to the url instead of the lesswrong post).

I ran through the manual tests.

This should be good to go.

**Comment by wezm** [comment]
I have taken some time to review this and have identified a few things that need addressing:

* If you attempt to submit a link but get the CAPTCHA wrong (shown to low karma users), then resubmit with the correct CAPTCHA the submission ends up as an article instead of link.
* If you submit a link that has already been submitted you are shown a little flash message (pictured) that states you can resubmit it, clicking this does not work. screen shot 2016-08-12 at 4 00 40 pm
* The size of the editor on the article view is a lot smaller than it is on the live site. I think the new size is unsuitable for writing a long article.
* Inline validations no longer work. On the live site if you submit the article form with nothing filled in you get an error against the title indicating this it is required. Additionally similar errors should be shown on the link submission form.
* Articles are referred to as articles in most places on this site so can you change the label of the tab on the submission page from, "Text Article", to "Article".

**Comment by jglamine** [comment]
Thank for catching these issues. I'll reproduce them and update the PR with fixes.

**Comment by jglamine** [comment]
I was able to reproduce your bugs. Two of them were a bit tricky to reproduce. Here are the steps:

### Bug 1 - Links turn into articles:
1. Click "Create new article"
1. Switch to the link tab.
1. Fill in info, submit.

Expected behavior: brings you to the page for a newly created link
Actual behavior: brings you to the page for a newly created article

### Bug 2 - article editor is too small:
1. Click "Submit a new link"
1. Switch to the article tab

Expected behavior: the text editor is 475px tall.
Actual behavior: the text editor is 84px tall.

**Comment by jglamine** [comment]
PR updated.

I was not able to reproduce the "That link has already been submitted." flash message. If it still happens, please provide me with steps to reproduce and let me know what browser you're using.

Changes are as follows:
* Fixed inline validation on article submission page.
 * Due to how the validation code is written, only one new error is displayed per submission of the form. So if you're missing both URL and title, it will initially only show a message next to the url.
* Changed title of the article tab to "Article"
* Prevent article editor from being too small when switching tabs.
* Prevent links from turning into articles when switching tabs.

When you get a chance, I'd love to get your feedback on this.

**Comment by jglamine** [comment]
Also note that there is not much validation around URLs. For example, links don't have to be valid urls. I don't think it's that important because people won't upvote broken links. If it turns out we really want better validation, we can always do it in another issue.

Also note that it's not possible to edit a link after submitting it, only the title. If we want admins to be able to edit links, we can do that as a separate issue. They can still delete them or edit the title, which should be enough for now.

**Comment by wezm** [comment]
> I was not able to reproduce the "That link has already been submitted." flash message. If it still happens, please provide me with steps to reproduce and let me know what browser you're using.

**Comment by wezm** [comment]
This looks good now. I'll deploy in the morning. For future reference I'd prefer you didn't force update an existing PR. If you add commits to address feedback it's easier for me to review just those changes instead of needing to review all changes again.

**Comment by wezm** [comment]
Deployed

**Pull request merged**
